### ISSUE TITLE
Status Bar is lost

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#102]
**Describe the bug**
When starting the IDE the status bar is lost.
With a trick I can get it back.
- opening prefs
- change tab to code

**To Reproduce**
Open the IDE

**Expected behavior**
The status bar should correctly loaded.

**Screenshots**
<img width="1232" alt="no status bar" src="https://user-images.githubusercontent.com/6450325/67593140-c6c1f880-f761-11e9-9bca-b98e32ba3008.png">
<img width="1232" alt="with status bar" src="https://user-images.githubusercontent.com/6450325/67593141-c6c1f880-f761-11e9-9c43-edff70e47bc7.png">

**Desktop (please complete the following information):**
 - OS macOS Catalina
 - Version 0.0.2

**Comment by per1234** [comment]
Hi @sstaub . Thanks so much for taking the time to report this!

Would you mind downloading [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4) and letting us know whether the bug still occurs?

There have been some nice advancements since the time of your report, so I think the issue might have been fixed along the way.
