### ISSUE TITLE
Not uploading to Uno - intermittent.

### ISSUE THREAD

**Issue by Durakill** [arduino/arduino-pro-ide#109]
Sketch compiles fine, without error.

Uploading to Uno appears to take place without error.

However, sketch has not uploaded.

Unfortunately, problem is intermittent. 

Just now, I disconnected the Uno, and reconnected it. The board is now communicating - sketch downloaded, and serial monitor is reporting data. However, I think this fix is also intermittent - sometimes works, sometimes not. 

I am happy enough to send you log files or similar if you wish.

Thanks,

Michael Flynn

OS X 10.14.6

**Comment by kittaakos** [comment]
> Sketch compiles fine,

@Durakill, can you please share your sketch file?

**Comment by kittaakos** [comment]
> I am happy enough to send you log files or similar if you wish.

Please do so.

Without the logs, I've assumed the following use-case: due to a bug in the CLI we were not able to close the serial monitor port and disconnect, hence the upload failed because the serial monitor was using the port. This issue has been fixed in the  CLI (see #157) and I have completely rewritten the serial-monitor feature. (see #112)

**Comment by Durakill** [comment]
Hi,

The problem has not recurred after downloading a more recent version the IDE. Thank you for your efforts. 

Regards, 

Michael Flynn

**Comment by kittaakos** [comment]
Thank you for the update, I am going to close this issue.

Please reopen if required.
