### ISSUE TITLE
STM32 and ST-link V2 interface problem

### ISSUE THREAD

**Issue by shanmugam10** [arduino/arduino-pro-ide#125]
board manager for the smt32 blue pill has been installed. Port is not detecting in Arduino ide for ST link. I can't change my upload method like regular arduino ide.

**Comment by per1234** [comment]
Hi @shanmugam10 . Thanks so much for taking the time to report this important issue!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4). The problem was that the first priority for upload support was devoted to using serial ports, as is most common with Arduino boards, but the ST-Link is a pure USB device that doesn't present a serial port. But now the Arduino Pro IDE supports uploading even if you don't have a port selected.

For anyone interested, we had a nice discussion about this issue in https://github.com/arduino/arduino-pro-ide/issues/364, which was about the same issue as it applied to the DigiSpark boards.
