### ISSUE TITLE
Processor's internal EEPROM editor tab.

### ISSUE THREAD

**Issue by cirobruno** [arduino/arduino-pro-ide#131]
The suggestion regards an opportunity to improve productivity during programming routines wich use processor's internal EEPROM.

Why not including a tab for direct editing the EEPROM content? I think about something like a table with 16 or 32 columns, showing EEPROM data in ASCII or HEX format, by user's choice. The user should be able to edit and burn its content toward the device's EEPROM. 

So far, I've been writing sketches exclusively for placing data in EEPROM. They're written in parallel to its respective main sketch (the runtime one). When programming, every time the main sketch requires any change in EEPROM content, I must switch to the EEPROM targeted program and upload it into the device. Then, I switch back to the main program.

I guess this improvement would be specially valuable for people who employ internal EEPROM data, such as texts for LCD displays or serial communication protocols.

**Comment by ubidefeo** [comment]
In the future we will be implementing support for external 3rd party tools (à la Arduino Java IDE).
This could be a good idea for a tool, but very niche since few modern microcontrollers actually have EEPROM anymore.
The effort required to develop something like this far exceeds doing it in the shell with any editor.
Closing
