### ISSUE TITLE
error selecting another card other than arduino

### ISSUE THREAD

**Issue by lucasviniciu** [arduino/arduino-pro-ide#145]
hello dude has a critical problem with board selection, example: select and download a board from espresff and so on. well fix that anything talk to me

**Comment by lucasviniciu** [comment]
@ @ @ @ @ @ @ @ eu

**Comment by per1234** [comment]
Hi @lucasviniciu . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
