### ISSUE TITLE
Find in files do not work

### ISSUE THREAD

**Issue by dronecz** [arduino/arduino-pro-ide#15]
**Describe the bug**
When I have multiple tabs open in my project,  search in files do not work. I´m able to find what I´m looking in one tab, but not in all tabs. 

![image](https://user-images.githubusercontent.com/16454728/67150531-d43a3700-f2b8-11e9-8144-4638ee280670.png)
![image](https://user-images.githubusercontent.com/16454728/67150542-f5028c80-f2b8-11e9-91a1-6779650836d1.png)

 - OS: Windows 7 x64 Pro SP1; Windows 10 (1903)

**Comment by kittaakos** [comment]
@dronecz, where is your `test.h` and the two opened `sketch_october19c.ino` files on the file system?

**Comment by dronecz** [comment]
These were just temporary files which I created in that time, but I think test.was at my Desktop. Files from dark screenshot are stored in my Dropbox folder.

**Comment by spoenemann** [comment]
I created an issue here: https://github.com/eclipse-theia/theia/issues/6867

**Comment by per1234** [comment]
Hi @dronecz . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
