### ISSUE TITLE
Cannot use Serial1

### ISSUE THREAD

**Issue by salmandos** [arduino/arduino-pro-ide#152]
When verified MultiSerial this problem showed up on Serial1.available() and Serial1.read()

> Cannot initialize object parameter of type 'UARTClass' with an expression of type 'USARTClass'

![image](https://user-images.githubusercontent.com/50876536/69638007-9d360e80-1038-11ea-9087-fd6ca1bdae28.png)

OS: Windows 10 1903

**Comment by per1234** [comment]
Hi @salmandos . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
