### ISSUE TITLE
Cannot open edit support when there are special symbols in the path

### ISSUE THREAD

**Issue by torenrl** [arduino/arduino-pro-ide#163]
**Describe the bug**
When a sketch is opened from a path with a special symbol, in my case a dollar sign ($), this does not work. (Since the path is in my work domain, I am not able to change this)

edit: The sketch in question was created using the arduino classic ide

**To Reproduce**
1. Create a sketch folder under a path with a dollar sign in a folders name (probably other special symbols as well)
2. Open the sketch

**Expected behavior**
Error message:

Could not start editor support.
open \foldername$\ ... \My Documents\Arduino\IRrec_test: The system cannot find the path specified.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.0.3a

**Comment by per1234** [comment]
Hi @torenrl . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
