### ISSUE TITLE
Does not retain port 

### ISSUE THREAD

**Issue by ianlyonthomas** [arduino/arduino-pro-ide#18]
**Describe the bug**
Loaded OK but on Launch get An unexpected error occurred when locating the Git executable. Continues to work despite error message.

Created new sketch (Blink) but when I try to upload = error - no port 
Selected Arduino Uno WiFi Rev 2 on port three. This diplayed OK but then showed as unavailable. 
To overcome, have to select board and port again and quickly click upload before the port drops again.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10

**Comment by per1234** [comment]
Hi @ianlyonthomas. Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
