### ISSUE TITLE
impossible to close a tab

### ISSUE THREAD

**Issue by joysfera** [arduino/arduino-pro-ide#193]
**Bug**
It's impossible to close opened files in tabs. There's no button/widget for that, there's no hotkey (AFAIK) and there's no File->Close menu entry.

**Expected behavior**
A tab has a close widget. Ideally also Ctrl+F4 hotkey works for closing a tab.

**Screenshots**
![tabs](https://user-images.githubusercontent.com/2862144/73529753-85538000-4417-11ea-8116-95b10f1b9979.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Comment by kittaakos** [comment]
Thanks for logging, it is intentional. You have to toggle between the _Advanced_ and _Classic_ modes (top right corner on the toolbar). If the _Advanced_ mode is active, then you can close the editors as you wish.

![Screen Shot 2020-01-31 at 13 07 20](https://user-images.githubusercontent.com/1405703/73538226-b8ebd580-442a-11ea-9d1e-d7d08a26c8c9.jpg)


Please reopen if required.

**Comment by joysfera** [comment]
Wonderful, thank you! May I suggest you to modify the defaults to let the IDE always start in the _Advanced_ mode then? Just to avoid this super confusion not only I fell into.

**Comment by kittaakos** [comment]
> Wonderful, thank you! May I suggest you to modify the defaults to let the IDE always start in the _Advanced_ mode then? Just to avoid this super confusion not only I fell into.

CC: @mastrolinux

**Comment by dp-cronton** [comment]
Although you can close a tab in this way, closing a tab is not really an Advanced feature. This should be available in classic mode. (I use Arduino mainly for teaching students aged 17-18 and we would porbably use the classic mode for most students and they should be able to close tabs, when its ready for use.)
