### ISSUE TITLE
Bug no autocomplete

### ISSUE THREAD

**Issue by Ferreira31** [arduino/arduino-pro-ide#205]
*Version 0.0.4
Muitas coisa ja melhorou no autocomplete, mas algumas funções basicas continuam não aparecendo, por exemplo a Serial 
![image](https://user-images.githubusercontent.com/59669264/73991033-b2c58f80-4929-11ea-8d9a-f72cc6d37224.png)

**Comment by owennewo** [comment]
Are you on windows 10?  Could be the same issue as I had - see #210

**Comment by per1234** [comment]
Hi @Ferreira31. Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
