### ISSUE TITLE
 library auto code a

### ISSUE THREAD

**Issue by lucasviniciu** [arduino/arduino-pro-ide#224]
hello arduino friends, I love the pro ide but like him and pro... go there you can put a COMPLETE library in the arduino that detects in the code that does not have in the ide the library sweet potato.h then it lowers 
and my tip      @love

**Comment by ubidefeo** [comment]
@masci @cmaglie @rsora 
my brain is hurting. is this spam?

**Comment by lucasviniciu** [comment]
man I speak portuguese my translation and get fucked anyway LOL @Mw

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Ubi de Feo <notifications@github.com>
Enviado: Tuesday, March 3, 2020 3:12:01 PM
Para: arduino/arduino-pro-ide <arduino-pro-ide@noreply.github.com>
Cc: lucasviniciu <lucasvinicius.lv149@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [arduino/arduino-pro-ide] library auto code a (#224)


@masci<https://github.com/masci> @cmaglie<https://github.com/cmaglie> @rsora<https://github.com/rsora>
my brain is hurting. is this spam?

**Comment by per1234** [comment]
Hi @lucasviniciu . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
