### ISSUE TITLE
Board search not reliable

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-pro-ide#263]
**Describe the bug**
It appears that search won't look for string match in `board.name` but only look for the prefix boardname.

**To Reproduce**
1. Make sure you have `arduino:avr` core installed
2. Click on "select other board or port"
3. Type "duemila" (for Arduino Duemilanove or Diecimila)
4. No results will be presented
5. Type "dieci" (for the same boards)
6. Duemilanove or Diecimila will appear in the results

**Expected behavior**
One would expect the search to happen in the strings comprising the board name.
In the specific case look for the content of `diecimila.name=Arduino Duemilanove or Diecimila`

**Screenshots**
![Screenshot 2020-06-04 at 15 36 45](https://user-images.githubusercontent.com/1894487/83764375-28443100-a67a-11ea-8e9b-7b041b28aad9.png)
![Screenshot 2020-06-04 at 15 36 53](https://user-images.githubusercontent.com/1894487/83764415-34c88980-a67a-11ea-89e2-a012c712bdc3.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 10.14.6

**Additional context**
n/a

**Comment by ubidefeo** [comment]
Also by just typing "arduino" in the search field if you have esp8266 core installed it will show a board named "arduino" and let you select it, which will bring up an error on compile
<img width="1054" alt="Screenshot 2020-06-04 at 15 49 06" src="https://user-images.githubusercontent.com/1894487/83765969-1bc0d800-a67c-11ea-8de8-12ceb2fe037b.png">
<img width="996" alt="Screenshot 2020-06-04 at 15 52 50" src="https://user-images.githubusercontent.com/1894487/83766027-29765d80-a67c-11ea-8276-ab6fc188376b.png">
<img width="1054" alt="Screenshot 2020-06-04 at 15 48 42" src="https://user-images.githubusercontent.com/1894487/83766070-36934c80-a67c-11ea-96e3-48bd95279165.png">

**Comment by kittaakos** [comment]
The first part of the issue has been fixed. We support fuzzy-search for the boards:

![Screen Shot 2020-07-20 at 16 07 15](https://user-images.githubusercontent.com/1405703/87947359-7f278d80-caa3-11ea-90e4-eeaa3fda767d.jpg)
![Screen Shot 2020-07-20 at 16 07 23](https://user-images.githubusercontent.com/1405703/87947365-7fc02400-caa3-11ea-8a85-be5332aecc5d.jpg)
![Screen Shot 2020-07-20 at 16 07 38](https://user-images.githubusercontent.com/1405703/87947368-8058ba80-caa3-11ea-9e58-bb7cd52621c9.jpg)
![Screen Shot 2020-07-20 at 16 08 20](https://user-images.githubusercontent.com/1405703/87947370-80f15100-caa3-11ea-8652-44f0561677ac.jpg)
![Screen Shot 2020-07-20 at 16 08 35](https://user-images.githubusercontent.com/1405703/87947372-8189e780-caa3-11ea-8415-4d872c8129eb.jpg)
![Screen Shot 2020-07-20 at 16 08 51](https://user-images.githubusercontent.com/1405703/87947375-8189e780-caa3-11ea-9c60-02b4e4b18085.jpg)
----

Regarding the second part of the issue and the `arduino-esp8266 is not a valid FQBN` error; it is tracked already [here](https://github.com/arduino/arduino-pro-ide/issues/272). The problem is caused by the hyphen (`‐`) in the FQBN. I have already removed the flawed FQBN validation and we rely on the CLI from the Pro IDE.

I consider this task as done and will be available in the next release.

**Comment by ubidefeo** [comment]
yes!
thank you, @kittaakos

**Comment by kittaakos** [comment]
> I consider this task as done

I  do not like the fuzzy search as-is; I am going to rework the boosting a bit.
