### ISSUE TITLE
Fails to open completely on Windows

### ISSUE THREAD

**Issue by Lamar26108** [arduino/arduino-pro-ide#269]
On my Windows 10 computer the IDE fails to open completely. It never gets past this point:

![slow_ide](https://user-images.githubusercontent.com/66745573/84301051-31714a00-ab21-11ea-8871-158991f522b2.JPG)

**Comment by kittaakos** [comment]
What's the error if you start the app from a command line? Please open `CMD.exe` and start `"Arduino Pro IDE.exe"`

**Comment by Lamar26108** [comment]
Good afternoon Akos,

I did exactly as you told me to in the email, but I waited ten minutes  and
it still didn't work. It stayed like this:

**Comment by Lamar26108** [comment]
The command prompt threw this error:

**Comment by per1234** [comment]
Hi @Lamar26108. Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.

**Comment by Lamar26108** [comment]
Thanks, it actually had been working in some of the previous versions.
