### ISSUE TITLE
Debugger hangs. 

### ISSUE THREAD

**Issue by twillert02** [arduino/arduino-pro-ide#297]
Working on Window10 laptop. with ArduinoZero
alpha 006 ,  compiling OK, update OK. serial monitor OK.
But after selecting debugger and select start debug

gdb starts and is halted as usual but then it does not continue or restart!
The debugger hangs though I still can edit, compile and update. no problem there

The alpha006 isn unzipped on C:\  but I tried several other locations, all with same result:
No debugging possible.

**Comment by per1234** [comment]
Hi @twillert02 . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
