### ISSUE TITLE
Autocomplete lacks semicolons

### ISSUE THREAD

**Issue by Rainbowz4U** [arduino/arduino-pro-ide#314]
When typing commands that normally require a semicolon at the end, the autocomplete is able to guess and fill in the command, but it always lacks a semicolon at the end, causing a compiler error.

**Screenshots**
<img width="513" alt="Screen Shot 2020-08-25 at 11 41 02 AM" src="https://user-images.githubusercontent.com/31143914/91196294-f4503900-e6c7-11ea-90aa-0c36ce53b946.png">
<img width="322" alt="Screen Shot 2020-08-25 at 11 41 15 AM" src="https://user-images.githubusercontent.com/31143914/91196296-f4e8cf80-e6c7-11ea-9e3d-626b9a325433.png">

**Desktop:**
 - OS: macOS Catalina
 - Version 0.1.0

**Comment by kittaakos** [comment]
Thanks for reporting it, @Rainbowz4U. This is definitely not a bug, but the expected behavior, so I tend to remove the bug label and replace with enhancement.

I have been working with several IDEs, tools, and editors in the past, but the automatic semicolon insertion was never part of the IntelliSense feature. Can you name a tool/IDE that does the semicolon insertion after auto-complete? Does VS Code, for example, with the C++ development extension supports it?

**Comment by kittaakos** [comment]
This VS Code extension could help to support this feature request: https://marketplace.visualstudio.com/items?itemName=seunghwan.smartsemicolon

**Comment by Rainbowz4U** [comment]
I tested within VS Code, and the IntelliSense in the C++ extension does add in semicolons for you. I was able to have it work with just the C++ extension, and no need for the smart semicolon.
<img width="505" alt="Screen Shot 2020-08-25 at 12 38 00 PM" src="https://user-images.githubusercontent.com/31143914/91202500-e7374800-e6cf-11ea-835a-25a2451fd0a2.png">
<img width="137" alt="Screen Shot 2020-08-25 at 12 38 12 PM" src="https://user-images.githubusercontent.com/31143914/91202501-e7374800-e6cf-11ea-9f3e-01b0f9928e5b.png">

**Comment by kittaakos** [comment]
> the IntelliSense in the C++ extension does add in semicolons for you.

Thank you for your help! The screenshot you have attached is a template and not a symbol if I am not mistaken. Does it also work if you auto-complete a method? Maybe this [can be configured](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense) without any additional extensions, I am just not yet aware of it.

**Comment by Rainbowz4U** [comment]
I tested again, and it has trouble auto-completing methods. It seems to only work for simple commands, as when I type in a method, it only fills in the name without parameters, parenthesis, or the semicolon. The current IntelliSense in the Pro IDE encounters the same issue.

**Comment by ubidefeo** [comment]
@Rainbowz4U 
I am using it the way I always have used intellisense:
* type the function name
* get suggestion
* TAB to parameter(s)
* TAB once again to exit the signature and add the semi-colon at the end

maybe because I got used to manually add that extra TAB to place the semicolon or exit the signature in order to chain more commands for one-liners
