### ISSUE TITLE
Basic commands underlined as error

### ISSUE THREAD

**Issue by OslafEman** [arduino/arduino-pro-ide#316]
Arduino-pro-ide 0.1.0 highlights as error basic commands such as delay, serial, wifi, etc.

**To Reproduce**
Open any code that contains these commands

**Screenshots**
![Anotación 2020-08-25 210737](https://user-images.githubusercontent.com/43764333/91247181-4ec4b600-e717-11ea-9cc5-137b14ca0ef1.png)

**Desktop (please complete the following information):**
 Windows 10 2004

**Comment by ubidefeo** [comment]
@kittaakos 
something to do with the LS support when ESP is selected?

**Comment by kittaakos** [comment]
@OslafEman, which board did you select when you had this error? Have you installed the corsponding core?

**Comment by OslafEman** [comment]
Hi @kittaakos, thanks for the prompt reply. I have selected the MH ET LIVE ESP32 MiniKit board and also installed the corresponding core.

![Anotación 2020-08-26 112842](https://user-images.githubusercontent.com/43764333/91330803-8707db00-e78f-11ea-9ed3-582e631fc4e1.png)

**Comment by per1234** [comment]
Hi @OslafEman . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
