### ISSUE TITLE
Autocomplete for .cpp and .h files

### ISSUE THREAD

**Issue by LumitoLuma** [arduino/arduino-pro-ide#333]
**Is your feature request related to a problem? Please describe.**
I cannot use Autocomplete function in `.h` and `.cpp` files or similar ones.

**Describe the solution you'd like**
I would enable autocomplete for those extensions, like `.ino` files have.

**Comment by per1234** [comment]
Hi @LumitoLuma. Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
