### ISSUE TITLE
Can't upload to Curiosity Nano AVR128DA48

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#420]
**Describe the bug**
Using the DxCore https://github.com/SpenceKonde/DxCore

The upload to the Curiosity Nano board work fine with Arduino IDE 1.8.13 on macOS Big Sur
but fails with the Arduino Pro IDE 0.13 nightly20210205
Upload error: Error: 2 UNKNOWN: uploading error: uploading error: exit status 1
It seems that the Pro IDE doesn't know the programmer. Maybe it is a problem that DxCore
use a new version of AVRDude which supports better upload with UDPI

**To Reproduce**
1. In Tools (see also screenshot)
- Programmer Atmel nEDGB
- Chip AVR128DA48 
2. Try to upload, compiling works
3. see screenshot

**Expected behavior**
Upload with nEDGB should work

**Screenshots**
<img width="780" alt="Bildschirmfoto 2021-02-08 um 14 42 30" src="https://user-images.githubusercontent.com/6450325/107228186-a7191700-6a1c-11eb-8613-ddd37c28e9fb.png">
<img width="1482" alt="Bildschirmfoto 2021-02-08 um 14 41 31" src="https://user-images.githubusercontent.com/6450325/107228195-a97b7100-6a1c-11eb-84bb-edb6f0d73c21.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2
 - Version: 0.1.13 nightly20210205

**Comment by per1234** [comment]
Hi @sstaub. You've rediscovered a bug you were the first to report last summer. You might recall this https://github.com/arduino/arduino-pro-ide/issues/309

The problem is that Arduino Pro IDE doesn't support this capability:
https://arduino.github.io/arduino-cli/dev/platform-specification/#upload-using-programmer-by-default

But not to worry, there is an easy fix: Just use **Sketch > Upload Using Programmer**.

**Comment by sstaub** [comment]
Ok, thank you . I forgot that the problem have fix.
