### ISSUE TITLE
Dark Mode optimization in Board and Port selection

### ISSUE THREAD

**Issue by nikilase** [arduino/arduino-pro-ide#46]
It may not be a bug and more of an annoyance but when I use dark mode and open the Board and Port selection window i don't see what I type in the search window and some boards in the list are barely readable. Would be nice if they would change the text colour a bit to make it better readable.
Happened on Windows 10 but probably the same colour palette on every OS.

<img width="573" alt="Arduino_a" src="https://user-images.githubusercontent.com/38077998/67163307-a5ca6380-f36d-11e9-82b2-62403014b82f.png">
<img width="573" alt="Arduino_b" src="https://user-images.githubusercontent.com/38077998/67163310-a7942700-f36d-11e9-839f-6ce9fa880c78.png">

**Comment by kittaakos** [comment]
Thanks for reporting it, @nikilase.

It was already fixed in the [`0.0.3` preview release](https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.3-alpha.preview). I am closing it.

![Screen Shot 2020-01-29 at 11 25 13](https://user-images.githubusercontent.com/1405703/73348724-30363380-428a-11ea-9723-713add26fc92.jpg)
